# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rafaelssucupira
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-http
# "service" is the name of this project. This will also be added to your AWS resource names.
service: image-analysis

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rekognition:DetectText
          Resource: "*"  
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: "*"   
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "*"   
resources:
  Resources:
    boxzapTable: 
      Type: AWS::DynamoDB::Table
      Properties : 
        TableName : box
        AttributeDefinitions : 
          - AttributeName: box_id
            AttributeType: S
          - AttributeName: box_data
            AttributeType: S
        KeySchema : 
          - AttributeName: box_id
            KeyType : HASH  
          - AttributeName: box_data
            KeyType : RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1    
    boxzapBucket: 
      Type : AWS::S3::Bucket  
      Properties:
        BucketName: boxzap

