# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rafaelssucupira
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-http
# "service" is the name of this project. This will also be added to your AWS resource names.
service: image-analysis

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rekognition:DetectLabels
          Resource: "*"  
        - Effect: Allow
          Action:
            - translate:TranslateText
          Resource: "*"   

functions:
  img-analysis:
    handler: src/index.main
    events:
      - httpApi:
          path: /analyse
          method: get
